name: build

on:
  push:
    branches:
      - master
  pull_request:
env:
  resourceRunID: ${{ github.run_id }}-${{ github.run_number }}

jobs:
  Build:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ Ubuntu-24.04 ]
        prepare: [ sudo apt-get update && sudo apt-get install -y exiftool imagemagick xdg-utils libimage-exiftool-perl zsh jq xorg ]
        include:
          - os: macos-15
            prepare: export PATH=/opt/homebrew/bin:$PATH && brew install exiftool imagemagick jq

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: false
      - name: Prepare ${{ matrix.os }} environment
        run: |
          ${{ matrix.prepare }}

      - name: Install git-diff-image
        run: |
          ./install.sh
